# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.synced_folder "~/Computer", "/home/vagrant/Computer"
  config.vm.provision :shell, :path => "setup/install.sh"

  config.vm.network "forwarded_port", guest: 80, host: 8080,
    auto_correct: true

  config.vm.provision "docker"
end
