# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.synced_folder "~/Computer", "/home/vagrant/Computer"
  config.vm.provision :shell, :path => "setup/install.sh"

  config.vm.network "forwarded_port", guest: 80, host: 8080,
      auto_correct: true
  config.vm.network "forwarded_port", guest: 8000, host: 8000,
        auto_correct: true
  config.vm.network "forwarded_port", guest: 9000, host: 9000,
        auto_correct: true

  config.vm.provision "docker"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = "2"
  end
end
